version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build:
    commands:
      - echo Build started on `date`
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./publish_output/**/**