version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build:
    commands:
      - echo Build started on `date`
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c Release -r linux-x64
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./Domain/bin/Release/netcoreapp3.1/linux-x64/publish/**/*
    - ./QuoteAPI/bin/Release/netcoreapp3.1/linux-64x/publish/**/*