version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build:
    commands:
    - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./publish_output
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - ./publish_output/**/**